/*
 * sys_fram_pubic__PRMTR_ATTR_LISTS_COMMON_ACQUISITION_INDEXES.h
 *
 *  Created on: Apr 9, 2017
 *      Author: ozgurbas
 */

#ifndef INC_SYS_FRAM_PUBIC__PRMTR_ATTR_LISTS_COMMON_ACQUISITION_INDEXES_H_
#define INC_SYS_FRAM_PUBIC__PRMTR_ATTR_LISTS_COMMON_ACQUISITION_INDEXES_H_



#endif /* INC_SYS_FRAM_PUBIC__PRMTR_ATTR_LISTS_COMMON_ACQUISITION_INDEXES_H_ */
